#############################################################################
# Makefile for building move_tetra
# Generated by tmake at 11:27, 2004/09/24
#     Project: move_tetra
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -finline -Winline -g -DDEBUG -DALTERN -DDAMPED -DCONSTVOL
CXXFLAGS=	-pipe -finline -Winline -LANG:std -g -DDEBUG -DALTERN -DDAMPED -DCONSTVOL
INCPATH	=	-I. -I/usr/X11R6/include
LINK	=	g++
LFLAGS	=	-LANG:std
LIBS	=	$(SUBLIBS) -L/usr/X11R6/lib -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	
SOURCES =	intersect_triangle.c \
		move_tetra.C
OBJECTS =	intersect_triangle.o \
		move_tetra.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	move_tetra
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: makefile

makefile: move_tetra.pro
	tmake move_tetra.pro -o makefile

dist:
	$(TAR) move_tetra.tar move_tetra.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) move_tetra.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f core.*

####### Sub-libraries


###### Combined headers


####### Compile

intersect_triangle.o: intersect_triangle.c \
		intersect_triangle.h

move_tetra.o: move_tetra.C \
		animal/support/trackball.h \
		animal/geometry/quaternion.h \
		animal/geometry/vec3.h \
		animal/traits/numerics.h \
		animal/integration/explicit_driver.h \
		animal/integration/driver.h \
		intersect_triangle.h \
		scheme.h \
		animal/integration/explicit_solver.h \
		animal/integration/solver.h \
		force.h \
		particle.h

